---
title: "Random Sample"
author: "Gwendolyn Reynolds"
date: "6/27/2017"
output: html_notebook
---

 

```{r setup, include=FALSE, echo=FALSE, warning=FALSE}
# Load packages 
library(knitr)
library(readxl)
library(scales)
library(forcats)
library(lubridate)
library(stringr)
library(tidyverse)
library(ggplot2)
library(stringr)
library(forcats)
library(magrittr)
library(stargazer)

# Echo=FALSE means the code does not show up in the document
# Caching allows you to re-run the report quickly
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(message = T) #Use F to suppress all messages from chunks for finalized report
knitr::opts_chunk$set(warning = T) #Use F to suppress all warnings from chunks for finalized report


# Settting the default resolution of plots
knitr::opts_chunk$set(dpi = 300)

# You can't just set the working directory when using .rmd in Knitr, so we set the root directory
# This is to make it easy to load data from the google drive
# All figures and cache are still saving in the same directory as the .rmd (don't commit these)
setwd("~/Google Drive/SI/DataScience/Misc/RandomSample/")
knitr::opts_knit$set(root.dir = '~/Google Drive/SI/DataScience/Misc/RandomSample/')

# Sorenson Impact design: a list of colors we use in ggplot
SI_design <- list(pacific = "#1D4F53", atlantic = "#18303C", carbon = "#6d6f71", granite = "#bcbdbf", silver = "#e6e7e7", arctic = "#107D7F")
SI_colorplot <- function() {data.frame("color" = names(unlist(SI_design)), "code" = unlist(SI_design), stringsAsFactors = F) %>% ggplot() + geom_rect(aes(fill = I(code)), xmin = 0, xmax = 1, ymin = 0, ymax = 1) + facet_wrap(~color)} #shows you our color options!

# This will fill bar colors with Sorenson Impact colors and default to theme_minimal
update_geom_defaults("bar", list(fill = SI_design$pacific))
update_geom_defaults("smooth", list(colour = SI_design$pacific, fill = SI_design$granite, alpha = I(2/10)))
update_geom_defaults("point", list(colour = SI_design$pacific, fill = SI_design$pacific))
theme_set(theme_minimal())

```


```{r draw in data and draw random sample, echo=FALSE}
preschoolnames <- read_csv("./RandomSampleforBilly.csv")

set.seed(123)
index <- sample(1:nrow(preschoolnames), 120)
index

preschoolnamesrandom <- preschoolnames[index, ]
write.csv(preschoolnamesrandom, "./RandomlyDrawnWinners.csv")

```

